# Generated by Django 2.1.2 on 2018-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_riyas'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_ty',
            field=models.BooleanField(default=True),
        ),
    ]
